# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=255)),
                ('art_content', models.TextField()),
                ('art_img', models.CharField(max_length=255)),
                ('art_status', models.CharField(max_length=50)),
                ('art_publish_date', models.DateTimeField(auto_now_add=True)),
                ('art_number_views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_content', models.TextField()),
                ('Comment_status', models.BooleanField(default=1)),
                ('Comment_parent_id', models.IntegerField()),
                ('Comment_art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
        ),
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=255)),
                ('keyword_art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_img', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=255)),
                ('user_status', models.BooleanField(default=1)),
                ('user_secret_quation', models.CharField(max_length=255)),
                ('user_secret_answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_user_like',
            field=models.ManyToManyField(to='article.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='art_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.User'),
        ),
    ]
